service:
    nexus:
      images: sonatype/nexus3
      container_name: nexus
      hostname: nexus
      
      restart: unless-stopped

      ports:
        - "8081:8081"

      volumes:
        - nexus-data:/nexus-data

      environment:
        INSTALL4J_ADD_VM_PARAMS: >-
          -Xms2g
          -Xmx2g
          -XX:MaxDirectMemorySize=2g
          -Djava.util.prefs.userRoot=/nexus-data/javaprefs

      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081"]
        interval: 30s
        timeout: 10s
        retries: 5

      ulimits:
        nofile:
          soft: 65536
          hard: 65536

      networks:
        nexus:
      logging:
        driver: json-file
        options:
          max-size: "20m"
          max-file: "5"



networks:
  nexus:
    driver: bridge
volumes:
  nexus-data: 
